apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: opa-policy
data:
  access_policy.rego: |
    package example

    default allow_access = false

    allow_access if input.age >= 18