apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opa-policy

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: opa-policy
  app.kubernetes.io/instance: opa-policy 